services:
  stt-api:
    build:
      context: ../../../STT-API-Server  # Path to your forked STT source
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8060:8000"
    volumes:
      - stt_models:/app/models
      - stt_cache:/app/cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      - "dockge.description=Custom STT API Server (jim0237 fork)"
      - "dockge.icon=headphones"
      - "dockge.note=Development version with custom features"

volumes:
  stt_models:
    name: stt-models
  stt_cache:
    name: stt-cache